version: '3'

services:
  gotenberg:
      image: thecodingmachine/gotenberg:6
      ports:
        - "3000:3000"

  web:
    image: php:7.3-apache
    container_name: php73
    volumes:
      - ./:/var/www/html/
    ports:
      - 8000:80